### ISSUE TITLE
Unknown environment "ganttchart"

### ISSUE THREAD

**Issue by emakei** [HeyFlash/emacs-stuff#2]
Get error when export to html. Same problem with Pdf.

**Comment by HeyFlash** [comment]
Uh-oh, I have not worked on this for a long time. It sounds to me like you have not included #+LATEX_HEADER: \usepackage{pgfgantt}
in your file (see manual). This only works for pdf export, html export is not supported.

Please note that currently the branch "no-hashes" works best.
I have been meaning to get back to this, but I never find the time.

**Comment by emakei** [comment]
Thanks for fast answer!
I'm include '#+LATEX_HEADER: \usepackage{pgfgantt}' to my org file. And when export to tex it contain's \usepackage{pgfgantt}. But when export from tex to pdf get error. When export to html get two files (MathJax.js and translator.css) and text ''Unknown environment "ganttchart". Maybe i need import something or define? I'm noob in this. Use emacs few months.
P.S. My OS is Windows 8.1

**Comment by HeyFlash** [comment]
Hmm, I don't know which latex system you are using. If it does not automatically ask to install required packages, maybe you need to do it manually. Try installing the pgfgantt package in your latex system. https://www.ctan.org/pkg/pgfgantt?lang=en
And then try to compile a normal latex with a pgfgantt chart (like from the examples in the documentation of the package). If you get pgfgantt to work, this should work as well.

**Comment by emakei** [comment]
I tried compile file (i'm use TexWorks, MikTex) and get an error like "can't use symbol Э (...)" in LaTeX. I think should use only latin symbols. I think so because when i tried to compile your example it make nice pdf, and when i tried to export to html got "Unknown environment "tikzpicture". Can you help with it issue? Or give me advice in which direction should i search?

**Comment by HeyFlash** [comment]
As I already said, exporting to html does not work. pgfgantt is a latex package that uses tikz. What org-gantt does is replace the dynamic block with hardcoded latex stuff, so that cannot work in html.

When you say that my example works, that indeed sounds like a problem with the file encoding. Depending on what you are doing, using the package inputenc may help:
https://www.ctan.org/pkg/inputenc?lang=en
If you use utf8, use \usepackage[utf8]{inputenc}
But if those are mathematical symbols you are using you might want to use latex fragments and latex math mode:
http://orgmode.org/manual/LaTeX-fragments.html

**Comment by emakei** [comment]
Problem solved by adding strings `\usepackage{cmap}
\usepackage[russian]{babel}` in outputted LaTeX buffer. Or `#+LATEX_HEADER: \usepackage{pgfgantt}
#+LATEX_HEADER: \usepackage{cmap}
#+LATEX_HEADER: \usepackage[russian]{babel}` in Org file, but after exporting in tex it's contains `\usepackage[russian, english]{babel}` and fatal error while export to pdf. After deleting `, english` it work.
P.S. but only on Debian )) On windows it doesn't work.
